name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
      branch:
        default: 'main'
        required: false
        type: string

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Create release branch
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ inputs.version }}
          echo $VERSION > VERSION
          git add VERSION
          ./gradlew jreleaserChangelog
          git add CHANGELOG.md
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git commit -a -m "release: v$VERSION"
          git push origin ${{ inputs.branch }}:release-${{ inputs.version }}

  assemble:
    name: Assemble ${{ matrix.os }}
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release-${{ inputs.version }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build distribution
        run: |
          ./gradlew package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-release-artifact
          path: |
            build/compose/binaries/main/deb/jreleaser-playground_${{ inputs.version }}-1_amd64.deb
            build/compose/binaries/main/dmg/jreleaser-playground-${{ inputs.version }}.dmg
            build/compose/binaries/main/msi/jreleaser-playground-${{ inputs.version }}.msi

  release:
    name: Release
    needs: [ prepare, assemble ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release-${{ inputs.version }}
          fetch-depth: 0

      - name: Download deb artifact
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-release-artifact
          path: build/compose/binaries/main

      - name: Download dmg artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-release-artifact
          path: build/compose/binaries/main

      - name: Download msi artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-release-artifact
          path: build/compose/binaries/main

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          JRELEASER_COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          JRELEASER_COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
        run: |
          ./gradlew jreleaserFullRelease

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-output
          path: |
            build/jreleaser/trace.log
            build/jreleaser/output.properties

      - name: Create release PR
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/mnonnenmacher/jreleaser-playground/pulls \
            -d '{"title":"Release ${{ inputs.version }}","body":"Release ${{ inputs.version }}","head":"release-${{ inputs.version }}","base":"main"}'
